# Generated by Django 5.1.1 on 2024-09-09 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0003_userprofile_mobile"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="mobile",
        ),
    ]
