# Generated by Django 5.1.1 on 2024-09-09 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0004_remove_userprofile_mobile"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="mobile",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
