# Generated by Django 5.1.1 on 2024-09-09 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0005_userprofile_mobile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="mobile",
            field=models.CharField(default=False, max_length=50),
        ),
    ]
