# Generated by Django 5.1.1 on 2024-09-09 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0006_alter_userprofile_mobile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="mobile",
            field=models.IntegerField(),
        ),
    ]
