# Generated by Django 5.1.1 on 2024-09-09 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0008_alter_userprofile_mobile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="zipcode",
            field=models.CharField(max_length=20),
        ),
    ]
