# Generated by Django 5.1.1 on 2024-09-10 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0009_alter_userprofile_zipcode"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="role",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
